apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: mlops-lab
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-buckets
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Creating bucket mlflow-artifacts..."
              mc alias set myminio http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb -p myminio/mlflow-artifacts || true
              mc mb -p myminio/dvc-remote || true
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: mlops-minio-credentials
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mlops-minio-credentials
                  key: MINIO_ROOT_PASSWORD
