apiVersion: v1
kind: Service
metadata:
  name: mlops-api-nodeport
  namespace: mlops-lab
  labels:
    app: mlops-api
spec:
  type: NodePort
  selector:
    app: mlops-api
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080    # optional, picked range 30000â€“32767
      protocol: TCP
